### ISSUE TITLE
Garnierite Melting Point

### ISSUE THREAD

**Issue by Tacete** [GregTech6-Unofficial/GregTech6-Unofficial#28] opened 2021-01-14 17:59 UTC
Purified Garnierite Ore shows a melting point of 891K on the tooltip and in NEI under crucible smelting.  However, as it creates Nickel, it actually melts at 1728K which is higher than the stated boiling point of Garnierite (1638K).

**Comment by Miradae** [comment] 2021-01-20 16:49
This is normal, many materials have this behavior in Gregtech 6

**Comment by Tacete** [comment] 2021-01-20 17:10
That seems like an issue to me... it is very disconcerting melting things in the crucible and watching it go well past the tooltip melting point before it becomes a liquid.  If it does not melt at the stated melting point what exactly is happening at that temperature?  If nothing is happening what is the point of the misleading tooltip?

**Comment by Miradae** [comment] 2021-01-20 17:13
It does melt but then forms to a totally different material with a different melting point

**Comment by yuesha-yc** [comment] 2021-01-22 13:54
@Miradae is correct. Ores transform to the heat-reduced metal when temperature surpasses the Ore's "Melting Temp". Many other ores have the same mechanic. Closed as it is not a bug.

**Closed as completed by yuesha-yc** 2021-01-22 13:54 UTC
